workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        # ⚠️ Mets ici EXACTEMENT le bundle identifier que tu utilises
        # dans Apple Developer / Codemagic UI (ex: "YumeApp" ou "com.yumedine.connect")
        BUNDLE_ID: "YumeApp"

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Set bundle id in Xcode project
        script: |
          # Remplace le PRODUCT_BUNDLE_IDENTIFIER dans le .pbxproj
          sed -i '' -E \
          "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" \
          ios/Runner.xcodeproj/project.pbxproj

      - name: Build IPA
        script: flutter build ipa --release -t lib/main.dart

    # Laisse Codemagic gérer la signature (UI -> iOS code signing -> Automatic + API Key)
    publishing:
      app_store_connect:
        auth: api_key
        submit_to_testflight: true


