name: yume_dine_connect
description: Simple WebView wrapper for Yume Dine Connect
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"
  remove_alpha_ios: true
